version: 2
jobs: 
  build: 
    machine: true
    steps:
      - checkout

      #build image
      - run: |
        docker info
        docker build -t micahcmapp -f Dockerfile .

      #deploy the image
      - run: |
        docker login --username=veronicalswoodward@gmail.com --password=938b0922-e336-4a58-b09f-c7ecaf689c47
        docker tag micahcmapp registry.heroku.com/micahcustomermanager/web
        docker push registry.heroku.com/micahcustomermanager/web
        curl https://cli-assets-heroku.com/install.sh | //cli-assets-heroku.com/install.sh | //cli-assets-heroku.com/install.sh | sh
        heroku container:release web -a micahcustomermanager
