version: 2.1

orbs:
  win: circleci/windows@1.0.0
  
jobs: 
  build: 
    executor:
      name: win/vs2019
      shell: powershell.exe
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "micahcustomermanager.csproj" }}
            
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "micahcustomermanager.csproj" }}
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - run:
          name: "Test the executable"
          command: .\bin\Release\netcoreapp3.1\win10-x64\publish\micahcustomermanager.exe
      - store_artifacts:
          path: .\bin\Release\netcoreapp3.1\win10-x64\publish\micahcustomermanager.exe

      #build image
      - run: 
        docker info:
        docker build -t micahcmapp -f Dockerfile .

      #deploy the image
      - run: 
        docker login --username=veronicalswoodward@gmail.com --password=938b0922-e336-4a58-b09f-c7ecaf689c47
        docker tag micahcmapp registry.heroku.com/micahcustomermanager/web
        docker push registry.heroku.com/micahcustomermanager/web
        curl https://cli-assets-heroku.com/install.sh | //cli-assets-heroku.com/install.sh | //cli-assets-heroku.com/install.sh | sh
        heroku container:release web -a micahcustomermanager




   
