

version: 2.1

orbs: 
  win: circleci/windows@2.2.0
jobs:
 build:
   executor: win/default
   steps:
     - checkout 

     # build image
     - run: |         
         docker info
         docker build -t micahcmapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         curl -X POST https://api.heroku.com/apps \
         -H "Accept: application/vnd.heroku+json; version=3" \
         -H "Authorization: Bearer $HEROKU_API_KEY"
         heroku update
         HEROKU_DEBUG=true HEROKU_DEBUG_HEADERS=1 heroku login
         cat ~/.netrc
         heroku auth:token
         docker tag micahcmapp registry.heroku.com/micahcmapp/web
         docker push registry.heroku.com/micahcmapp/web 
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a micahcmapp



   
